# Camunda Platform 7
camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
  autoDeploy:
    enabled: false
  disable-backoff-strategy: true

# Camunda Platform 8
# local configuration:
#zeebe.client:
#  broker:
#    gateway-address: localhost:26500
#  security:
#    plaintext: true
#
# SaaS configuration:
#zeebe.client:
#  cloud:
#  region: bru-2
#  clusterId:
#  clientId:
#  clientSecret: